### ISSUE TITLE
Mocking a HTTP 204 No Content response

### ISSUE THREAD

**Issue by eifinger** [aresponses/aresponses#66]
Hi,
I'd like to mock a API which for some methods returns the status code 204 and `None` as the body.

I tried a few ways to implement it with this lib but failed.

```python
# No Content response HTTP 204
aresponses.add("foo.com", "/", "get", aresponses.Response(body=None, text=None, status=204))
url = "http://foo.com"
async with aiohttp.ClientSession() as session:
    async with session.get(url) as response:
        text= await response.text()
        assert text is None

Can you point me in a direction to mock a `None` response body?

**Comment by brycedrennan** [comment]
`None` is a python type and thus cannot be returned across http.  If you intended to send the text `"None"` then you'd just need to set body to `"None"`

**Comment by eifinger** [comment]
Thank you! Upon further inspection the api does indeed return an empty string.
