### ISSUE TITLE
pytest-asyncio as requirement

### ISSUE THREAD

**Issue by guillempuigcom** [aresponses/aresponses#67]
I've tried to follow the `pytest-asyncio` topic evolution (https://github.com/aresponses/aresponses/issues/52)

I've seen the PR #55 was closed due to breaking compatibilities with `aiohttp` later on.

Is absolutely necessary to install either `pytest-aiohttp` or `pytest-asyncio`?
Is it considered in a near future to tackle this? (We would prefer not to install any test pkg if possible)

Thanks in advance

**Comment by brycedrennan** [comment]
Last I checked, which was several months ago, `aresponses` works with either, `pytest-aiohttp` or `pytest-asyncio`.  To use an async test fixture, an event loop fixture is necessary, so yes I believe one of these must be installed.  

What exact situation are you encountering? Did you see 
https://github.com/aresponses/aresponses#working-with-pytest-aiohttp
and https://github.com/aresponses/aresponses/pull/57 ?
